EmpresaT3/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmpresaT3.Areas.Identity.Data;
using EmpresaT3.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Net.Mail;

namespace EmpresaT3.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacto
        [Authorize]
        public async Task<IActionResult> MensajesLista()
        {
            try
            {
                return View(await _context.Contacto.OrderByDescending(s => s.Id).ToListAsync());
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }

        // GET: Contacto/Create
        public IActionResult Index()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Id,Nombre,Email,Mensaje")] Contacto contacto)
        {
            try
            {
                ModelState.Remove("Fecha");
                ModelState.Remove("IpAddress");
                if (ModelState.IsValid)
                {
                    TimeZoneInfo tzone = TimeZoneInfo.FindSystemTimeZoneById("Argentina Standard Time");
                    DateTime dt = DateTime.UtcNow;
                    var datetime2 = TimeZoneInfo.ConvertTimeFromUtc(dt, tzone).ToString();

                    Contacto nuevoMensaje = new()
                    {
                        Nombre = contacto.Nombre,
                        Email = contacto.Email,
                        Mensaje = contacto.Mensaje,
                        Fecha = datetime2,
                        IpAddress = RemoteIP.GetClientIP(),
                    };
                    _context.Add(nuevoMensaje);
                    await _context.SaveChangesAsync();
                    this.TempData["messages"] = "Su consulta ha sido enviada con éxito";

                    return RedirectToAction(nameof(Index));
                }
                this.TempData["messages"] = "Error";
                return View(contacto);
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }




        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || _context.Contacto == null)
                {
                    return NotFound();
                }

                var contacto = await _context.Contacto
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (contacto == null)
                {
                    return NotFound();
                }

                return View(contacto);
            }
            catch(Exception)
            {
                return NotFound("Error");
            }
            
        }

        // POST: Contacto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (_context.Contacto == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Contacto'  is null.");
                }
                var contacto = await _context.Contacto.FindAsync(id);
                if (contacto != null)
                {
                    _context.Contacto.Remove(contacto);
                }



                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MensajesLista));
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }

        private bool ContactoExists(int id)
        {
            return _context.Contacto.Any(e => e.Id == id);
        }
    }
}

EmpresaT3/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmpresaT3.Areas.Identity.Data;
using EmpresaT3.Models;
using Microsoft.AspNetCore.Authorization;
using EmpresaT3.Core;

namespace EmpresaT3.Controllers
{
    [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
    public class LogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Logs
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _context.Logs.OrderByDescending(s => s.Id).ToListAsync());
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }

        // GET: Logs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || _context.Logs == null)
                {
                    return NotFound();
                }

                var logs = await _context.Logs
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (logs == null)
                {
                    return NotFound();
                }

                return View(logs);
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }

        // POST: Logs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (_context.Logs == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
                }
                var logs = await _context.Logs.FindAsync(id);
                if (logs != null)
                {
                    _context.Logs.Remove(logs);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound("Error");
            }
            
        }

        private bool LogsExists(int id)
        {
          return _context.Logs.Any(e => e.Id == id);
        }
    }
}

EmpresaT3/Controllers/UserController.cs
using EmpresaT3.Areas.Identity.Data;
using EmpresaT3.Core;
using EmpresaT3.Core.Repositories;
using EmpresaT3.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace EmpresaT3.Controllers
{
    [Authorize(Roles = $"{Constants.Roles.Administrator}")]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserController(IUnitOfWork unitOfWork, SignInManager<ApplicationUser> signInManager)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            try
            {
                var users = _unitOfWork.User.GetUsers();
                return View(users);
            }
            catch
            {
                return NotFound("Error");
            }
            
        }

        public async Task<IActionResult> Hash(string id)
        {
            try
            {
                var user = _unitOfWork.User.GetUser(id);
                var roles = _unitOfWork.Role.GetRoles();

                var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

                var roleItems = roles.Select(role =>
                    new SelectListItem(
                        role.Name,
                        role.Id,
                        userRoles.Any(ur => ur.Contains(role.Name)))).ToList();

                var vm = new EditUserViewModel
                {
                    User = user,
                    Roles = roleItems
                };

                return View(vm);
            }
            catch(Exception)
            {
                return NotFound("Error desconocido");
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            try
            {
                if (userId == null)
                {
                    return NotFound();
                }

                var user = await _signInManager.UserManager.FindByIdAsync(userId);

                var rolesForUser = await _signInManager.UserManager.GetRolesAsync(user);

                if (rolesForUser.Count() > 0)
                {
                    foreach (var item in rolesForUser.ToList())
                    {
                        // item should be the name of the role
                        var result = await _signInManager.UserManager.RemoveFromRoleAsync(user, item);
                    }
                }

                await _signInManager.UserManager.DeleteAsync(user);
                await _signInManager.UserManager.UpdateSecurityStampAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View("Hash");
            }
            

            
        }




        [HttpPost]
        public async Task<IActionResult> OnPostAsync(EditUserViewModel data)
        {
            try
            {
                var user = _unitOfWork.User.GetUser(data.User.Id);
                if (user == null)
                {
                    return NotFound();
                }

                var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

                //Loop through the roles in ViewModel
                //Check if the Role is Assigned In DB
                //If Assigned -> Do Nothing
                //If Not Assigned -> Add Role

                var rolesToAdd = new List<string>();
                var rolesToDelete = new List<string>();

                foreach (var role in data.Roles)
                {
                    var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                    if (role.Selected)
                    {
                        if (assignedInDb == null)
                        {
                            rolesToAdd.Add(role.Text);
                        }
                    }
                    else
                    {
                        if (assignedInDb != null)
                        {
                            rolesToDelete.Add(role.Text);
                        }
                    }
                }

                if (rolesToAdd.Any())
                {
                    await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
                }

                if (rolesToDelete.Any())
                {
                    await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
                }

                user.FirstName = data.User.FirstName;
                user.LastName = data.User.LastName;
                user.Email = data.User.Email;

                _unitOfWork.User.UpdateUser(user);
                await _signInManager.UserManager.UpdateSecurityStampAsync(user);
                return RedirectToAction("Hash", new { id = user.Id });
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }

        }
    }
}

EmpresaT3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using EmpresaT3.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Iframe"] = @"<iframe name='myIframe' id='myIframe' width='300' height='400' src='/Contacto/MensajesLista/'></iframe>";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmpresaT3</title>
    <link rel="stylesheet" href="emperesa.css" asp-append-version="true">
    <link rel="stylesheet" href="_Layout.cshtml.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmpresaT3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light degrade border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> 
                    <img class="logo" src="/empresat3.png" alt="logo"width="160px"srcset="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                        @if(User.IsInRole("Manager") || User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Logs" asp-action="Index">Logs</a>
                            </li>
                            

                            //DROPDOWN DE MENSAJES
                            @*<div class="dropdown">
                              <li class="nav-item">
                                  <a class="nav-link">Mensajes</a>
                              </li>
                              <div class="dropdown-content">
                                @Html.Raw(ViewData["Iframe"])
                              </div>
                            </div>*@

                            <li class="nav-item">
                                <a class="nav-link" id="open">Mensajes</a>
                            </li>

                            <div id="popup" class="defa-context-panel">
                              <div>@Html.Raw(ViewData["Iframe"])</div>
                            </div>
                        }
                        @if(User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a>
                            </li>
                        }

                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmpresaT3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

     
</body>
</html>